apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: rule-api
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
