apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  # namespace: pricing-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: guhodza551/pricingplatform-apigateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ReverseProxy__Clusters__pricingCluster__Destinations__pricingDestination__Address
              value: http://pricing-api/
            - name: ReverseProxy__Clusters__ruleCluster__Destinations__ruleDestination__Address
              value: http://rule-api/
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
